import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Nav from "../components/Header.js";
import data from "/data/data.json";
import PlanetDescription from "../components/PlanetDescription";
import Stats from "../components/Stats";

export default function Mercury() {
  const [content, setContent] = useState(data[0].overview.content);

  return (
    <div className={styles.container}>
      <Head>
        <title>Planets | Mercury</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav activepage="mercury" />
        <PlanetDescription
          planetName={data[0].name}
          planetImg={data[0].images.planet}
          internalImg={data[0].images.internal}
          geologyImg={data[0].images.geology}
          overviewContent={data[0].overview.content}
          structureContent={data[0].structure.content}
          geologyContent={data[0].geology.content}
          overviewSrc={data[0].overview.source}
          structureSrc={data[0].structure.source}
          geologySrc={data[0].geology.source}
        />
        <Stats
          rotationTime={data[0].rotation}
          revolutionTime={data[0].revolution}
          radius={data[0].radius}
          temperature={data[0].temperature}
        />
      </main>
    </div>
  );
}
