import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Nav from "../components/Header.js";
import data from "/data/data.json";
import PlanetDescription from "../components/PlanetDescription";
import Stats from "../components/Stats";

export default function Neptune() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Planets | Neptune</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav activepage="neptune" />
        <PlanetDescription
          planetName={data[7].name}
          planetImg={data[7].images.planet}
          internalImg={data[7].images.internal}
          geologyImg={data[7].images.geology}
          overviewContent={data[7].overview.content}
          structureContent={data[7].structure.content}
          geologyContent={data[7].geology.content}
          overviewSrc={data[7].overview.source}
          structureSrc={data[7].structure.source}
          geologySrc={data[7].geology.source}
        />
        <Stats
          rotationTime={data[7].rotation}
          revolutionTime={data[7].revolution}
          radius={data[7].radius}
          temperature={data[7].temperature}
        />
      </main>
    </div>
  );
}
