import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Nav from "../components/Header.js";
import data from "/data/data.json";
import PlanetDescription from "../components/PlanetDescription";
import Stats from "../components/Stats";

export default function Saturn() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Planets | Saturn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav activepage="saturn" />
        <PlanetDescription
          planetName={data[5].name}
          planetImg={data[5].images.planet}
          internalImg={data[5].images.internal}
          geologyImg={data[5].images.geology}
          overviewContent={data[5].overview.content}
          structureContent={data[5].structure.content}
          geologyContent={data[5].geology.content}
          overviewSrc={data[5].overview.source}
          structureSrc={data[5].structure.source}
          geologySrc={data[5].geology.source}
        />
        <Stats
          rotationTime={data[5].rotation}
          revolutionTime={data[5].revolution}
          radius={data[5].radius}
          temperature={data[5].temperature}
        />
      </main>
    </div>
  );
}
