import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Nav from "../components/Header.js";
import data from "/data/data.json";
import PlanetDescription from "../components/PlanetDescription";
import Stats from "../components/Stats";

export default function Uranus() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Planets | Uranus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav activepage="uranus" />
        <PlanetDescription
          planetName={data[6].name}
          planetImg={data[6].images.planet}
          internalImg={data[6].images.internal}
          geologyImg={data[6].images.geology}
          overviewContent={data[6].overview.content}
          structureContent={data[6].structure.content}
          geologyContent={data[6].geology.content}
          overviewSrc={data[6].overview.source}
          structureSrc={data[6].structure.source}
          geologySrc={data[6].geology.source}
        />
        <Stats
          rotationTime={data[6].rotation}
          revolutionTime={data[6].revolution}
          radius={data[6].radius}
          temperature={data[6].temperature}
        />
      </main>
    </div>
  );
}
