import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Nav from "../components/Header.js";
import data from "/data/data.json";
import PlanetDescription from "../components/PlanetDescription";
import Stats from "../components/Stats";

export default function Venus() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Planets | Venus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav activepage="venus" />
        <PlanetDescription
          planetName={data[1].name}
          planetImg={data[1].images.planet}
          internalImg={data[1].images.internal}
          geologyImg={data[1].images.geology}
          overviewContent={data[1].overview.content}
          structureContent={data[1].structure.content}
          geologyContent={data[1].geology.content}
          overviewSrc={data[1].overview.source}
          structureSrc={data[1].structure.source}
          geologySrc={data[1].geology.source}
        />
        <Stats
          rotationTime={data[1].rotation}
          revolutionTime={data[1].revolution}
          radius={data[1].radius}
          temperature={data[1].temperature}
        />
      </main>
    </div>
  );
}
